# Generated by Django 3.0.8 on 2020-09-04 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_orderitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
    ]
