# Generated by Django 3.0.8 on 2020-09-14 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20200914_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Home/Garden', 'Home/Garden'), ('Books/Media', 'Books/Media'), ('Auto/Vehicles', 'Auto/Vehicles'), ('Others', 'Others')], max_length=200, null=True),
        ),
    ]
