# Generated by Django 3.0.8 on 2020-09-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20200914_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Home', 'Home'), ('Media', 'Media'), ('Auto', 'Auto'), ('Others', 'Others')], max_length=200, null=True),
        ),
    ]
